genet/core.py
genet/utils/google_directions.py
genet/utils/spatial.py
tests/test_utils_google_directions.py
tests/test_utils_spatial.py

Google direction methods now differentiate between networks that have the simplified tag and not. If a network is not simplified, they now use GeNet's own methods (previously osmnx).
As a bonus, I changed the [read method ](https://github.com/arup-group/genet/compare/google-directions-api-with-own-simplification#diff-462244c575997d50c1cb3baeec5285e1b7dc38b3df72e8a1430e0a848f6b55ddR51) to expect a path to a single file, as that's what the rest of the code produces. Just in case someone passes a folder with a number of different json files, which is likely, could be different json files generated by running the google requests at different times, that way you can have them all in the same folder. I think it's cleaner and less convoluted.
Annoyingly, google encoded polylines (when decoded) …

Google directions api uses GeNet's own simplification methods

---

scripts/simplify_network.py

See https://arupdigital.atlassian.net/browse/LAB-990
**After this change**:
```
$ python scripts/simplify_network.py --help
usage: simplify_network.py [-h] -n NETWORK [-s SCHEDULE] -p PROJECTION
[-np PROCESSES] -od OUTPUT_DIR
Simplify a MATSim network by removing intermediate links from paths
optional arguments:
-h, --help            show this help message and exit
-n NETWORK, --network NETWORK
Location of the network.xml file
-s SCHEDULE, --schedule SCHEDULE
Location of the schedule.xml file
-p PROJECTION, --projection PROJECTION
The projection network is in, eg. "epsg:27700"
-np PROCESSES, --processes PROCESSES
The number of processes to split computation across
-od OUTPUT_DIR, --output_dir OUTPUT_DIR
Output directory for the simplified network
```

Fix simplifications script's help message (LAB-990)

---

bash_scripts/.coveragerc
genet/outputs_handler/matsim_xml_writer.py
genet/variables.py
tests/test_outputs_handler_matsim_xml_writer.py

See https://arupdigital.atlassian.net/browse/LAB-1002 and https://github.com/arup-group/genet/issues/55
```
$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ python scripts/simplify_network.py -n /Users/mickyfitz/workspace/matesto/data/matsim12-test-town/network.xml -s /Users/mickyfitz/workspace/matesto/data/matsim12-test-town/transitschedule.xml -p epsg:27700 -od /tmp/genet
2021-02-16 21:32:27,877 - Reading in network at /Users/mickyfitz/workspace/matesto/data/matsim12-test-town/network.xml
2021-02-16 21:32:27,880 - Reading in schedule at /Users/mickyfitz/workspace/matesto/data/matsim12-test-town/transitschedule.xml
2021-02-16 21:32:28,306 - Simplifying the Network.
2021-02-16 21:32:28,306 - Begin simplifying the graph
2021-02-16 …
```

Make link 'oneway' attribute optional when writing networks to disk

---

genet/outputs_handler/geojson.py
genet/schedule_elements.py
tests/test_core_components_route.py
tests/test_core_components_service.py
tests/test_core_schedule.py
tests/test_core_schedule_elements.py
tests/test_outputs_handler_geojson.py

Fixes #61 
A couple of mode-related methods relied on modes data stored on the graph, which was not updated after the modes were changed. Modes are no longer saved on the graph and the methods use the Routes data directly. Relevant test before and after:

Lab 1046 ValueError: cannot set a frame with no defined index and a scalar

---

.github/workflows/build_pipeline.yml
.gitignore
CONTRIBUTING.md
bash_scripts/notebooks-smoke-test.sh
notebooks/1. Intro.ipynb
notebooks/5.1. Modifying Network - Basics.ipynb
notebooks/6.2. Validating Network - Google Directions API.ipynb
notebooks/notebook_smoke_tests.py
requirements.txt

See https://arupdigital.atlassian.net/browse/LAB-1051
Adds a python script to discover and execute all notebooks. 
I wrote this in Python rather than pure bash because of bash 3's lack of support for dictionaries/maps/associative arrays and other such limitations, but I am still invoking `nbconvert` as a bash command, rather than using the `nbconvert` [Python API](https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-using-the-python-api-interface). This is because Andrew Kay mentioned that the Python API is not supported on Windows.
I have added this smoke test to the CI build, which was already quite slow, and is now c. 2 minutes slower, but I think it's worth it.
The smoke test identified 3 notebooks with minor errors, all of which are fixed in this PR:

Mf lab 1051 notebook smoketests

---

genet/use/schedule.py
genet/utils/simplification.py
tests/test_core_network.py
tests/test_outputs_handler_geojson.py
tests/test_use_schedule.py

Fix multi edge simplify bug

---

genet/inputs_handler/matsim_reader.py
genet/outputs_handler/matsim_xml_writer.py
tests/test_core_schedule.py

Reading MATSim schedule, a transformer did not contain `always_xy=True` attribute resulting in a lat lon swap.

add missing always_xy=True to a couple of transformers

---

.gitignore
scripts/simplify_network.py

The network simplification tool had not been updated for the recent changes to GeNet's core network API. At the time I created this PR, I didn't think about the other scripts, but some of them will no doubt be suffering from the same problem - let's fix all of those in a different PR.

Fix network simplification script

---

scripts/generate_standard_outputs.py
scripts/inspect_google_directions_requests_for_network.py
scripts/make_road_only_network.py
scripts/reproject_network.py
scripts/send_google_directions_requests_for_network.py
scripts/simplify_network.py
scripts/validate_network.py

Fixes broken scripts post https://github.com/arup-group/genet/pull/73 as was done for the simplification script here: https://github.com/arup-group/genet/pull/79
It would be awesome to have automated tests for these scripts: [LAB-1185](https://arupdigital.atlassian.net/browse/LAB-1185) records that. I included example invocation for the scripts in that card (because I had to run them post fixing to check they work :D)
There is only one issue with the `send_google_directions_requests_for_network.py` which will not work properly unless we give it an api key. And I'm not sure how to fake it :D

Fix scripts

---

.github/workflows/build_pipeline.yml

Confirmed that the code bundles are still being pushed to S3 after the change (see the timestamp of the first zip file in the bucket, pushed by the build from this branch):
```bash
2021-09-06 10:02:09   12519807 c3JV2xc.zip
2021-08-27 21:41:44   12510767 V4WdWwF.zip
2021-08-27 21:38:43   12526325 s7iXEiJ.zip
2021-08-27 21:20:42   12527411 sfSWlJj.zip
...
```

Make S3 code bucket a CI build variable

---

genet/core.py
genet/outputs_handler/geojson.py
genet/utils/spatial.py
notebooks/7. Visualising Network.ipynb
tests/test_core_network.py
tests/test_outputs_handler_geojson.py
tests/test_utils_spatial.py

Adds method to generate geodataframes of PT routes which take geometries from network links referenced in their routes.
So we can generate pretty pictures like the one below. Also added to standard outputs, useful for validation. The geodataframe has mode, service and route id columns for easy subsetting, as well as route names for human ease.

PT network route GeoDataFrame and geojson output

---

genet/outputs_handler/geojson.py

Right now the generic network and schedule geojson outputs are in default network projection, this ensures the outputs match the rest of standard outputs: lat,lon projection, ready to be dropped into kepler
ATM it's outputting network crs with general outputs
after the change it's in lat lon

add reprojection param to general standard network geojson outputs

---

bash_scripts/code-coverage.sh
genet/core.py
genet/inputs_handler/gtfs_reader.py
genet/inputs_handler/read.py
genet/outputs_handler/geojson.py
genet/schedule_elements.py
genet/utils/dict_support.py
genet/utils/graph_operations.py
genet/utils/pandas_helpers.py
requirements.txt
tests/fixtures.py
tests/test_core_components_route.py
tests/test_core_components_service.py
tests/test_core_network.py
tests/test_core_schedule.py
tests/test_core_schedule_elements.py
tests/test_data/matsim/network.xml
tests/test_inputs_read.py
tests/test_utils_graph_operations.py
tests/test_utils_pandas_helpers.py
tests/test_utils_spatial.py

Closes #93 
Fixes a few hundred warnings - still a few hanging around.
I also had to bump pytest-related versions to make the parallel test stuff work on my local machine, and modified the number of processes so that it is automatically matched to the number of available processors reported by the machine.
I had a brief look at the `xfail` test, but couldn't see a quick fix for it.

Fix runtime warnings

---

requirements.txt

Experienced this error installing genet using conda:
```
#8 99.66 Collecting protobuf==3.0.0b3
#8 99.84   Downloading protobuf-3.0.0b3.tar.gz (117 kB)
#8 99.92   Preparing metadata (setup.py): started
#8 100.2   Preparing metadata (setup.py): finished with status 'error'
#8 100.2   ERROR: Command errored out with exit status 1:
#8 100.2    command: /opt/conda/envs/abmenv/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-38l64av7/protobuf_acc973556ec84528a74ca21fdf0e101d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-38l64av7/protobuf_acc973556ec84528a74ca21fdf0e101d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = …
```

upgrade protobuf

---

.github/workflows/build_pipeline.yml
genet/core.py
genet/utils/graph_operations.py
genet/utils/simplification.py
tests/test_core_network.py
tests/test_utils_simplification.py

During the simplification process, some links get simplified to loops. In cases of teleported PT, this results in undesirable routes.
For example, given a rail stop sequence: 
```
[A, B, C, D]
```
And the expected, teleported, route is: 
```
[A-A, A-B, B-B, B-C, C-C, C-D, D-D]
```
Right now GeNet oversimplifies the end points resulting in long loops, the route is:
```
[S1, B-B, B-C, C-C, S2]
```
the geometry is retained so they look like lines, but are actually very big loop links, i.e.
```
S1: 
from node: B 
to node: B 
```
Not tested, but the likely MATSim consequences are agents not being able to access the service at stops A and D, as MATSim does not use our complex geometry (it's just an additional attribute)
Change to defining 'end-points' during simplification - those are the nodes …

Fix loopy simplification

---

requirements.txt

The [notebooks smoke tests were failing in GitHub Actions builds](https://github.com/arup-group/genet/runs/5734236896?check_suite_focus=true) due to an error from `jinja2`, which is a transitive dependency of the `nbconvert` module we're using. 
Moving to the latest `nbconvert` [fixes this](https://github.com/arup-group/genet/runs/5735692884?check_suite_focus=true):

Upgrade nbconvert dependency version

---

genet/__init__.py
genet/inputs_handler/read.py
genet/use/road_pricing.py
tests/test_road_pricing.py

Gets rid of hard coded Cordon type road pricing. Allows user to specify the toll type, descriptions and allows for change in filenames. Defaults to link type tolling to align with hermes matsim module.

Generalise road pricing type

---

requirements.txt
setup.py

When trying to install `scop`:
This is a spurious version clash - it is almost certain that both apps/libs will work with either version of `pytest-cov`.
We could decide to loosen the constraints for more than just these libraries, of course, but for now these will hopefully at least fix Scop's problem. Opinions welcome.
I may create a similar PR for MC that is much more flexible on the test dependencies, but still specific about non-test dependency.

Loosen version constraints for various pytest-related dependencies

---

.github/workflows/daily-scheduled-ci.yml

A minimal daily scheduled CI build that runs the unit tests in an attempt to uncover any problems caused by having loosened the version constraints on some of our dependencies.
See https://arupdigital.atlassian.net/browse/LAB-1639.
Note that, for security reasons, new Actions workflows do not run until they have been created in the default branch, so we won't see this scheduled build start to run until after this PR has been merged.

Add a minimal daily scheduled CI build

---

notebooks/notebook_smoke_tests.py
requirements.txt

You can now optionally pass one or more notebook paths as params to the python script, where before you could pass only a directory from which the list of notebooks would be discovered.
This was mostly just to give me a faster feedback loop than running all the notebooks while working on these changes, but could still be generally useful in situations where you're making changes to one or two notebooks and want the same sort of fast feedback. For example:
```bash
python notebooks/notebook_smoke_tests.py -k genet \
-n 'notebooks/1. Intro.ipynb' \
-n 'notebooks/2.4. Reading CSV data.ipynb' \
-n 'notebooks/3.3. Writing GTFS data.ipynb' \
-n 'notebooks/4.3. Using Network - Routing.ipynb' \
-n 'notebooks/4.4. Using Network - Auxiliary Files referencing Network IDs.ipynb'
```
**NB:** The …

Improve notebooks smoke test report

---

.gitignore
notebooks/notebook_smoke_tests.py

Exactly the same as [LAB-1905](https://arupdigital.atlassian.net/browse/LAB-1905).
Nearly 4.5 minutes running locally
Around 4 minutes running in the CI build
Around 1m 15s running locally
Around 2 minutes running in the CI build
The notebooks now run in parallel and finish in a non-deterministic order. They appear in the summary table printed to console at the end of the tests in the (non-deterministic) order that they finished .  _Technically_ it was always the case that they appeared in order of finish, but that was also always name alphabetical order, because we sorted the list and then worked through it sequentially in series. 
Do we care that the table is no longer alphabetically sorted? It's a quick fix if we do.

Use multiprocessing in the notebooks smoketest

---

genet/core.py
scripts/separate_modes_in_network.py

Adds a script to split given modes from the links on the network graph from under the `'modes'` attribute. You end up with a graph with many more links, the links with mentioned modes exists only with that mode, all other attributes are copied across (for the time being anyway, we might have to set/scale capacity/speed eventually).
Context: We use Hermes in MATSim, which results in slower vehicles, like bikes, blocking cars on links. Creating separate links for that mode is an initial solution to that problem.
Bonus: Noticed a lag with method that adds links. Because with this script we're adding links with the same from and to nodes, we need to generate a multi-index (links are stores in the graph in this format: `(from_node, to_node, multiindex)`). One line, which gives a closer initial …

Split (active) modal subgraphs

---

genet/utils/elevation.py
scripts/add_elevation_to_network.py
tests/test_data/elevation/link_slopes.xml
tests/test_utils_elevation.py

While testing a multimodal network for the Sheffield ABM, we realised that MATSIM uses a separate `link_slopes.xml` rather than using the link slope written as attribute onto the network links. This PR adds a function `write_slope_xml` and edits the `add_elevation_to_network.py` script to use it.

Updating the elevation script to write elevation.xml

---

genet/schedule_elements.py
tests/test_core_components_route.py
tests/test_core_schedule.py

Found when working on TE, using the method to generate trips from headways on a `Route` object level breaks the graph schema underlying the schedule. Test catching it before and after:
Added a similar test for schedule too for good measure, but there was no problem there.

fix method setting trips from headway breaking graph schema

---

genet/__init__.py
genet/utils/elevation.py
scripts/add_elevation_to_network.py

Fixes:
- clashing argument flags `-ws`
- `import genet.utils.elevation as elevation` being overwritten by `elevation = args['elevation']` and preventing [`write_slope_to_object_attribute_file`](https://github.com/arup-group/genet/compare/elevation-script-fixes?expand=1#diff-99b2946aac5db3dd9ee2030e299fe866323e2dc3d2ed02fd93e16d1d066708edL142-R144)
As a bonus:
- gets rid of `elevation_output_dir = os.path.join(output_dir, 'elevation')` it's a needless extra folder (nothing gets saved anywhere else). User can decide if they want outputs saved to a folder called elevation or not

Elevation script fixes

---

CHANGELOG.md
genet/core.py
genet/schedule_elements.py
tests/fixtures.py
tests/test_core_network.py
tests/test_core_schedule.py

As seen on one of our projects, deleting a link that served as an intermodal access/egress point to a PT stop resulted in the following MATSim error:
```java
java.lang.NullPointerException: Cannot invoke "org.matsim.api.core.v01.network.Link.getToNode()" because "link" is null
at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorRoutingModule.findCoordinate(SwissRailRaptorRoutingModule.java:97) ~[columbus-2.1.0-jar-with-dependencies.jar:2.1.0]
at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorRoutingModule.fillWithActivities(SwissRailRaptorRoutingModule.java:73) ~[columbus-2.1.0-jar-with-dependencies.jar:2.1.0]
at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorRoutingModule.calcRoute(SwissRailRaptorRoutingModule.java:60) ~[columbus-2.1.0-jar-with-dependencies.jar:2.1.0]
at …
```

Intermodal access egress validation

---

Dockerfile
requirements.txt

docker image is failing in main branch with 
```
#0 120.7        5495 | OGRFieldDomainShadow* CreateCodedFieldDomain( const char *name,
#0 120.7             |                       ^~~~~~~~~~~~~~~~~~~~~~
#0 120.7       g++ -pthread -shared build/temp.linux-aarch64-cpython-311/extensions/gnm_wrap.o -L../../.libs -L../../ -L/usr/local/lib -L/usr/lib -lgdal -o build/lib.linux-aarch64-cpython-311/osgeo/_gnm.cpython-311-aarch64-linux-gnu.so
#0 120.7       error: command '/usr/bin/gcc' failed with exit code 1
#0 120.7       [end of output]
#0 120.7   
#0 120.7   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 120.7   ERROR: Failed building wheel for gdal
...
#0 123.3           raise RuntimeError("CMake must be installed to build the following extensions: …
```

Fix docker image

---

CHANGELOG.md
Dockerfile
README.md

PR to https://github.com/arup-group/genet/pull/194 which converts all scripts to CLI.
This PR adds changes to `Dockerfile` to support this - I went with no entry point. My reasoning is that it makes it flexible to run both genet CLI and custom scripts without overriding the entry point - which is a bit of a headache if using an AWS batch job for example.
If the docker image is named something else, like 'cml-genet' then it doesn't look too crazy I think... (see the docs) - but I'm  looking for feedback on this decision.
Docker image is building: [slack build notification](https://arupconsulting.slack.com/archives/CNASXCHM2/p1698156704065569), and tests inside passing
```
$ docker run cml-genet python -m pytest -vv tests
...
=========== 1063 passed, 1 xfailed, 82 warnings in 279.00s …
```

Update `Dockerfile` and docs

---

README.md

Today was the first time I tried to install and test GeNet on my new(er) M2 machine, and I found that 15 unit tests were failing due to the absence of the CBC coiner solver, despite my having followed the installation instructions from the README. After figuring out what was missing, I have added two additional commands to the section of the README about installing native dependencies on a Mac.
You can see the rendered section of the README [here](https://github.com/arup-group/genet/tree/fix_macos_coiner_install_instructions#installing-the-native-dependencies).

Fix MacOS installation instructions for the coiner solver

---

Dockerfile

Fixes #211. 
I've purged `nodejs` while I'm here, but the main fix is copying the repo into a subdirectory of root and then pip installing it.

Clean up Docker image to fix hanging build

---

CHANGELOG.md
genet/output/geojson.py
genet/output/sanitiser.py
tests/test_output_sanitiser.py

Instead of filling empty values with a string: `"None"` we just leave them empty and operate on the values in the columns that have values. 
I think this was likely added so that empty values would show up in kepler, as `None` rather than disappearing completely. We don't use kepler much anymore, since it's not maintained anymore, and leaving the values empty is more true to the original geodataframe.

Fix saving geodataframes with empty geometry

---

.github/workflows/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/workflows/ISSUE_TEMPLATE/DOCS.yml
.github/workflows/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
.github/workflows/ISSUE_TEMPLATE/config.yml
.github/workflows/docs.yml
.gitignore
CONTRIBUTING.md
README.md
docs/api/cli.md
docs/contributing.md
docs/docker.md
docs/index.md
docs/installation.md
docs/overrides/main.html
docs/static/extras.css
docs/static/hooks.py
genet/core.py
genet/max_stable_set.py
genet/schedule_elements.py
genet/utils/graph_operations.py
mkdocs.yml
pyproject.toml
requirements/dev.txt

Move to github pages for the docs. 
This will render all the example notebooks and display them, so none of that information is lost from the wiki.
I've also moved most of the installation instructions to the docs and given use of Docker its own page.
I got about 60% of the way through updating the docstrings, but it is mind-numbing stuff so I focussed on the most important classes. I also updated type hinting as I was going along. 
Why update docstrings? If docstrings are set up correctly then when rendering the docs, it will pick up on inconsistencies between the function signature and the docstrings, so you can catch issues where you've updated your function sig but not your docstring. Also, I see lots of complaints from mypy now that I've updated type hinting enough for it to kick in …

Add github pages configuration and some basic docs pages

---

requirements/base.txt

Noticed a failing test in https://github.com/arup-group/genet/actions/runs/8471718196/job/23332569549?pr=232. It is caused by xarray [v2024.03](https://docs.xarray.dev/en/stable/whats-new.html#v2024-03-0-mar-29-2024) having the `.oindex` property which seems to be causing issues with our test's array comparison. This is fixed by pinning xarray.

Add xarray with version pinning to requirements

---

.cruft.json
README.md
docs/contributing.md
docs/installation.md
requirements/dev.txt

Fixes #239 by adding `-c city-modelling-lab` to the docs install instructions (incl. README).
Fixes broken CI in #232 by updating dev requirements from latest template changes.

Update docs and template

---

CHANGELOG.md
src/genet/cli.py
src/genet/core.py
tests/test_core_network.py

Closes: #244, second in a series of 3, to facilitate better active mode support

Method to split links depending on mode

---

CHANGELOG.md
src/genet/core.py
tests/test_core_network.py

Fixes: #248, in a wild turn of events, my projected 3 part PR series has grown to 4. I found this bug while working on #245. The fix is inversely proportional to the amount of time it took to diagnose and recreate the issue in a unit test..
I had to mock the method which gives the available multi-index for an edge in the graph because it would not give me the same behaviour as I was seeing with a larger dataset. The problem happens when this method outputs an available multi-index that is sandwiched by multi-indices already being used on the graph. In this small example it would always give me the largest index being used +1, which did not recreate the error.
Stripped from all the context, the problem was setting a dataframe with an output of a groupby (of the same dataframe) which has …

Bugfix: Multi-indexing fails in a very specific case

---

.cruft.json
.editorconfig
.github/workflows/commit-ci.yml
.github/workflows/daily-scheduled-ci.yml
.github/workflows/docs.yml
.github/workflows/pr-ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.pre-commit-config.yaml
CONTRIBUTING.md
docs/contributing.md
linkcheck.json

- Fixes #256 
I used `cruft update` to pull in the latest versions of the Actions workflows that are managed by the cookie-cutter template.
[Daily CI build failed](https://github.com/arup-group/genet/actions/runs/14086145639)
[Commit CI build succeeded](https://github.com/arup-group/genet/actions/runs/14091043334/job/39467520415)
```
(genet-conda-env) (genet-3.11.2) √ .github % pwd
/Users/mickyfitz/workspace/genet/.github
(genet-conda-env) (genet-3.11.2) √ .github % grep -iRn "mamba" .
(genet-conda-env) (genet-3.11.2) ?1 .github %
```

Remove references to mamba from CI workflows

---

.github/workflows/commit-ci.yml
.github/workflows/daily-scheduled-ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

- Fixes #256  
So, the PR I merged to fix the builds used the wrong git tag for some of the actions (`v1.1.1` doesn't exist; we need `v1.1.0` - see [here](https://github.com/arup-group/actions-city-modelling-lab/tags)). Unfortunately, one of the places where the tag was correct was (part of) the CI commit workflow, so the build was fixed for that workflow but broken for the Daily CI, so we only discovered it was broken after merging:
Any checks which are not relevant to the PR can be pre-checked by the PR creator.
All others should be checked by the reviewer(s).
You can add extra checklist items here if required by the PR.

Fix broken git tags in CI workflows
